### ISSUE TITLE
The CBOR library is sensitive to a DOS attack

### ISSUE THREAD

**Issue by vivekidem** [c-rack/cbor-java#119]
Hi Team,

According a specially crafted message, the library will try to allocate a message that is way above the memory capacity. 

For a CBOR array input. The code was trying to decode the CBOR array before trying to use the byte[]. The library that has no limit on the allocation memory that is requires -> an attacker could get craft a packet that will ask the library to allocate an object that will exceed the available memory.

**Comment by sbahloul** [comment]
Let me put a bit of background here: the problem is that library is trying to allocate an amount of memory that is too important for the environment that causes an OutOfMemoryError. So the library itself is not sensitive to a DOS attack, but sending a specially crafted package to a service that is relying on the library to parse CBOR, will generate a crash. 

Looking to implement a fix, we would like to confirm that introducing a limit in the amount of memory that could be allocated - typically for a ByteString or String allocation -  and if larger, the library would generate an (controlled) exception instead of an OOM. Would it be an acceptable solution ?

The anonymized stacktrace:
2021-09-18 00:47:30.229 7690-7814/XXX Throwing OutOfMemoryError "Failed to allocate a 761618456 byte allocation with 3783270 free bytes and 508MB until OOM, target footprint 7566542, growth limit 536870912" (VmSize 5977504 kB)
2021-09-18 00:47:30.230 7690-7814/XXX: FATAL EXCEPTION: Thread-11    Process: XXX, PID: 7690    java.lang.OutOfMemoryError: Failed to allocate a 761618456 byte allocation with3783270 free bytes and 508MB until OOM, target footprint 7566542, growth limit 536870912
        at java.io.ByteArrayOutputStream.<init>(ByteArrayOutputStream.java:77)
        at co.nstant.in.cbor.decoder.AbstractDecoder.decodeBytes(AbstractDecoder.java:70)
        at co.nstant.in.cbor.decoder.UnicodeStringDecoder.decodeFixedLength(UnicodeStringDecoder.java:58)
        at co.nstant.in.cbor.decoder.UnicodeStringDecoder.decode(UnicodeStringDecoder.java:32)
        at co.nstant.in.cbor.CborDecoder.decodeNext(CborDecoder.java:138)
        at co.nstant.in.cbor.CborDecoder.decode(CborDecoder.java::90)
        at co.nstant.in.cbor.CborDecoder.decode(CborDecoder.java:78)

**Comment by c-rack** [comment]
@vivekidem Would you like to make a PR that fixes this?

**Comment by vinaymjoshi** [comment]
@c-rack , from client side it can be mitigated by setting a definite value in setMaxPreallocationSize :

`try {
    val decoder = CborDecoder(ByteArrayInputStream(this))
    decoder.setMaxPreallocationSize(1024)
    return decoder.decode()
  } catch (e: CborException) {
    throw UnexpectedEndOfStream(message = "Invalid CBOR Encoded data ")
  }`
  
However if client side above config is not set, then there should be some default value from library side.
